### ISSUE TITLE
Serf members output looks like it was not deserialized

### ISSUE THREAD

**Issue by ThorodanBrom** [Silur/serfrpc-c#3]
On printing the string returned by `serf_members()`, all I get is some weird values. It looks like it is not deserialized properly.

Code:
`char* mems = serf_members()`
`printf("%s",mems)`

Output:
![serf_member_error](https://user-images.githubusercontent.com/9331293/56032751-814b5a00-5d40-11e9-9cde-6e50d7d4919e.png)

This is run only for one agent, my system - so I should at least get the one agent showing up.

**Comment by Silur** [comment]
Have you solved the issue or closed it because of my late response? 
I'll make sure to arrange some time and fix it, thanks for the input ant the PR :)

**Comment by ThorodanBrom** [comment]
Hello @Silur , I closed this issue as well as PR #4 in frustration - sorry for that!

With regard to solving this - I recall that when I was testing, `serf_members` gave proper output when _there was more than one member in the cluster_. At the moment, I cannot verify this, but I will do so later, and put a screenshot here.

If it's an issue of number of members, then I think the solution will be simple.
